source "https://rubygems.org"

# Jekyll für GitHub Pages
gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"

# Plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
